edahlseng/configuration-ci-general

- CHANGELOG.md
- package.json
> New Release

- CHANGELOG.md
- package.json
> New Release: test

- CHANGELOG.md
- package.json
> New Release: v1.3.2

- CHANGELOG.md
- package.json
> New Release: v1.4.0

- sources/index.yml
This pull request adds a Terraform executor, as well as several Terraform-related jobs:
* lint-terraform
* terraform-apply
* terraform-plan
* validate-terraform
> feat: Add Terraform-related jobs and executor

- CHANGELOG.md
- package.json
> New Release: v1.5.0

- CHANGELOG.md
- package.json
> New Release: v1.6.0

- CHANGELOG.md
- package.json
> New Release: v1.7.0

- CHANGELOG.md
- package.json
> New Release: v1.7.2

- CHANGELOG.md
- package.json
> New Release: v1.8.1

- CHANGELOG.md
- package.json
> New Release: v1.9.0

- CHANGELOG.md
- package.json
> New Release: v1.10.0

- CHANGELOG.md
- package.json
> New Release: v1.11.0

- CHANGELOG.md
- package.json
> New Release: v1.12.0

- CHANGELOG.md
- package.json
> New Release: v1.13.0

- CHANGELOG.md
- package.json
> New Release: v1.13.1

- CHANGELOG.md
- package.json
> New Release: v1.13.2

- CHANGELOG.md
- package.json
> New Release: v1.13.3

- CHANGELOG.md
- package.json
> New Release: v1.14.0

- CHANGELOG.md
- package.json
> New Release: v1.15.0

- CHANGELOG.md
- package.json
> New Release: v1.16.0

- CHANGELOG.md
- package.json
> New Release: v1.16.1

- CHANGELOG.md
- package.json
> New Release: v1.17.0

- CHANGELOG.md
- package.json
> New Release: v1.17.1

- CHANGELOG.md
- package.json
> New Release: v1.17.2

- CHANGELOG.md
- package.json
> New Release: v1.18.0

- CHANGELOG.md
- package.json
> New Release: v1.18.1

- CHANGELOG.md
- package.json
> New Release: v1.18.2

- CHANGELOG.md
- package.json
> New Release: v1.18.3

- CHANGELOG.md
- package.json
> New Release: v1.19.0

- CHANGELOG.md
- package.json
> New Release: v1.19.1

- CHANGELOG.md
- package.json
> New Release: v1.20.0

- CHANGELOG.md
- package.json
> New Release: v1.20.1

- sources/index.yml
This pull request adds a `check-docker-image-service-health` command.
> feat: Add check-docker-image-service-health command

- CHANGELOG.md
- package.json
> New Release: v1.21.0

- CHANGELOG.md
- package.json
> New Release: v1.21.1

- CHANGELOG.md
- package.json
> New Release: v1.22.0

- sources/index.yml
This pull request contains a number of fixes to the `create-release-pr` job (see commit messages for more details).
> Create release PR job fixes

- CHANGELOG.md
- package.json
> New Release: v1.22.2

- CHANGELOG.md
- package.json
> New Release: v1.23.0

- CHANGELOG.md
- package.json
> New Release: v1.23.1

- CHANGELOG.md
- package.json
> New Release: v1.24.0

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.25.0

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.26.0

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.27.0

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.27.1

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.28.0

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.29.0

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.29.1

- CHANGELOG.md
- package-lock.json
- package.json
> New Release: v1.30.0

- sources/index.yml
- Added `get-eks-token` command
- Updated `lint-terraform` job
> feat: Add `get-eks-token` command
